name: Action Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo "${{gituhub.token}}"
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: List Files After Checkout
        run: |
            pwd
            ls
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Roshan
      - name: Log Greet Time
        run: echo "${{steps.greet.outputs.time}}"